import { HIDE_DEMO_BADGES } from '@/lib/env';

interface AiBadgeProps {
  /** "AI" in tight contexts; "AI INSIGHT" where there's room. */
  label?: 'AI' | 'AI INSIGHT';
}

/**
 * Subtle indicator that a section's content is (or will be) AI-generated.
 * Pairs visually with `DemoBadge` so the page reads as having a coherent
 * badge system: gray "Demo data" for mocked sections, navy "AI" for
 * AI-generated content.
 *
 * Suppressed alongside DemoBadge when `VITE_HIDE_DEMO_BADGES=true` for
 * clean screenshots.
 */
export function AiBadge({ label = 'AI INSIGHT' }: AiBadgeProps = {}) {
  if (HIDE_DEMO_BADGES) return null;
  return (
    <span
      className="inline-flex items-center gap-1 rounded-s bg-accent-wash px-1.5 py-0.5 text-[9.5px] font-semibold uppercase tracking-[0.08em] text-accent"
      title="Generated by Claude Sonnet 4.6"
    >
      <Sparkle />
      {label}
    </span>
  );
}

function Sparkle() {
  return (
    <svg
      width="10"
      height="10"
      viewBox="0 0 12 12"
      aria-hidden="true"
      className="block"
    >
      <path d="M6 1 L7 5 L11 6 L7 7 L6 11 L5 7 L1 6 L5 5 Z" fill="currentColor" />
    </svg>
  );
}
